### ISSUE TITLE
Login via Google / Torus fails. "node results do not match"

### ISSUE THREAD

**Issue by Hansbald** [zillet/zillet#72]
Hello,
until yesterday I could login normally, since today it is no longer working.

Clicking on Google Login opens a pop-up window in which I log into Google.
3 Loading dots appear, after about 30 seconds the window closes and zillet.io return the error "node results do not match" in the top right.

Any idea how to fix this would be appreciated.

Console log:

Access to XMLHttpRequest at 'https://api.infura.io/v1/jsonrpc/mainnet' from origin 'https://zillet.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

3970431.js:2 POST https://api.infura.io/v1/jsonrpc/mainnet net::ERR_FAILED

(index):1 Access to XMLHttpRequest at 'https://api.infura.io/v1/jsonrpc/mainnet' from origin 'https://zillet.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

3970431.js:2 POST https://api.infura.io/v1/jsonrpc/mainnet net::ERR_FAILED

3970431.js:2 POST https://torusnode.zilliqa.network/jrpc net::ERR_NAME_NOT_RESOLVED
3970431.js:2 POST https://torus-18.torusnode.com/jrpc net::ERR_CONNECTION_TIMED_OUT
3970431.js:2 POST https://torus.ont.io/jrpc net::ERR_CONNECTION_TIMED_OUT
3970431.js:2 POST https://torus.etherscan.com/jrpc net::ERR_CONNECTION_TIMED_OUT
3970431.js:2 POST https://torus.cosmos.network/jrpc net::ERR_CONNECTION_TIMED_OUT
3970431.js:2 POST https://torus.matic.network/jrpc net::ERR_CONNECTION_TIMED_OUT
3970431.js:2 POST https://torus.binancex.dev/jrpc net::ERR_CONNECTION_TIMED_OUT
3970431.js:2 POST https://torus-node.skalelabs.com/jrpc net::ERR_CONNECTION_TIMED_OUT
3970431.js:2 POST https://torus.ens.domains/jrpc net::ERR_CONNECTION_TIMED_OUT

**Comment by YZhenY** [comment]
hey guys. infura recently pulled down their v1 API causing this issue. 

Updating the torus directAuth SDK on zillet would resolve all issues here

**Comment by jano85** [comment]
> hey guys. infura recently pulled down their v1 API causing this issue.
> 
> Updating the torus directAuth SDK on zillet would resolve all issues here

Hi, how long will take that update ?
