### ISSUE TITLE
Support Page Display

### ISSUE THREAD

**Issue by thomashare** [zillet/zillet#76]
Please check the bottom of this page - https://support.zillet.io. It looks like some JSON code was misplaced. See below for what is shown.

`[ { "node": { "title": "Staking on Zillet", "path": "/staking-on-zillet", "excerpt": "When you stake your ZILs, your receive ZIL and gZIL (Governance ZIL) as a reward, this means you are allowed to vote on governance proposals on the Zilliqa ecosystem. But the best ", "date": "2020-10-23", "priority": 100 } }, { "node": { "title": "How to use your Ledger Nano S with Zillet", "path": "/getting-started/how-to-use-ledger-with-zillet", "excerpt": "Learn how to connect your very own Ledger Nano S hardware wallet to Zillet. Select account index you want to access, by default it is set to 0 and click on the “CONNECT” button", "priority": 100, "date": "25-09-2019" } }, { "node": { "title": "How to get started on Zillet", "path": "/getting-started/how-to-get-started-on-zillet", "excerpt": "Please take some time to understand this for your own safety. Your funds will be stolen if you do not heed these warnings. What is Zillet? Zillet is a free, open-source, client-side interface.", "priority": 100, "date": "23-07-2019" } }, { "node": { "title": "15 Simple tips to avoid phishing and scams", "path": "/security/avoid-phishing-and-scams", "excerpt": "A compilation of tips and tricks to avoid common phishing/scam techniques. Do not give your private key, mnemonic phrase, or keystore file to anyone. Never click on a link sent to you, even if it looks like it was sent by a legitimate crypto company", "priority": 100 } }, { "node": { "title": "How To Create a New Wallet", "path": "/getting-started/how-to-create-a-wallet", "excerpt": "Create a New Wallet. Select an option for a type of wallet to create. Enter a strong password. Click the `\"Create New Wallet\"` button. Download and safely save your Wallet File.", "priority": 90, "date": "23-07-2019" } }, { "node": { "title": "21 Common terms in Zilliqa/ Crypto community", "path": "/getting-started/common-terms", "excerpt": "Here is a list of terms you may encounter in Zilliqa or in other services on a daily basis. What is Account address, Private key, Gas Limit, Gas Price, Nonce, Keystore file, Mnemonice Seed, Scilla", "priority": 80, "date": "23-07-2019" } }, { "node": { "title": "7 Tips for the Beginners", "path": "/getting-started/tips-to-for-beginners", "excerpt": "We cannot reverse, cancel, or refund transactions. Make sure you know the process inside and out. Learn more about how can you secure your wallet and use all of it's features without getting scammed.", "priority": 70, "date": "23-07-2019" } } ]`

**Comment by man15h** [comment]
450411c86ade68df7114584fe94df4abac41ac29
