### ISSUE TITLE
Rewards claim fails

### ISSUE THREAD

**Issue by defyanse** [zillet/zillet#92]
Several days since the recent upgrade that took place, this error is denying me the ability to claim rewards and therefore transfer or unstake my assets. I'm using a Ledger Nano X, and all current firmware, software, and Zilliqa App version, Uninstalled and reinstalled the Zilliqa App. Cleared all browser and Ledger Live caches. Nothing so far has worked. Ledger is having an unresolved issue with 'DCR Explorer' but I am able to claim other token rewards. So far Zilliqa is the only one failing. Please help me resolve this. Thanks! (Des D'Costa
![image](https://user-images.githubusercontent.com/85447596/120929334-8d6f9f80-c69d-11eb-9cce-8dafdcb71e7d.png)
![image](https://user-images.githubusercontent.com/85447596/120929343-92ccea00-c69d-11eb-94b4-9efc29badb69.png)

Ledger Nano Issue:
![image](https://user-images.githubusercontent.com/85447596/120929519-328a7800-c69e-11eb-83f4-31c1053e8dd8.png)

**Comment by westphil3** [comment]
me too!!
but the red message is :
Error : Account balance is low, balance should be at least 100 ZIL
However I have 256 ZIL unclaimed reward

**Comment by defyanse** [comment]
> me too!!
> but the red message is :
> Error : Account balance is low, balance should be at least 100 ZIL
> However I have 256 ZIL unclaimed reward

I understand Zillet is aware of the issue and is working in a fix/update. No eta provided, but they did communicate this on the 6th June.

**Comment by westphil3** [comment]
Perfect !
Let's be patient ...

**Comment by westphil3** [comment]
No news ?

**Comment by westphil3** [comment]
it's strange
there are only two of us complaining

**Comment by defyanse** [comment]
Yes, that is strange. No, no news at all, either. I haven't tried today, but yesterday afternoon was a no go, still. I'm HODLing so not too worried, yet. Then again, I emailed support directly, and they responded from there. There's been nothing from here. If I do get some response or change, I'll update here. Perhaps you would too?

**Comment by westphil3** [comment]
Of course with pleasure

**Comment by westphil3** [comment]
It's okey for me
everything is in order
rewards claim succès

**Comment by defyanse** [comment]
Hey, glad to hear it. All the best!

des d'costa | c: 780.832.1732 | ***@***.***
Breathe easy. Drive like Satan is behind you. Live life.

**Comment by westphil3** [comment]
Nooooo !
transaction broadcasted but no trace of the transaction 24 hours later.
Zilliqa team did not respond to my email
you have to be patient

**Comment by defyanse** [comment]
That's crazy. There's a lot of unhappy folk on their Telegraph channel, too. Be very careful. I fell for a scam on their Telegraph site and my ZIL got emptied out. Odd that I could claim my reward but a scammer could and also got all my staked funds. So beware.  Their support & communication really does need work!

**Comment by westphil3** [comment]
It is done !!
everything works again finally
forward to staking

**Comment by defyanse** [comment]
Happy Hodling
